version: '3.8'

services:
  storybook:
    build:
      context: .
      target: storybook
      dockerfile: Dockerfile.dev
    image: stencil-auth0-storybook-local:latest
    ports:
      - '7910:7910'
    environment:
      IS_STORYBOOK: 'true'
    networks:
      - app-network
    volumes:
      - storybook_data_local:/var/www

  prisma-studio:
    build:
      context: .
      target: prisma-studio
      dockerfile: Dockerfile.dev
    image: stencil-auth0-prisma-studio-local:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5555:5555'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - prisma_studio_data_local:/var/www

volumes:
  storybook_data_local:
  prisma_studio_data_local:

networks:
  app-network:
    external: true
