version: '3.8'
services:
  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    environment:
      REDWOOD_API_URL: ${REDWOOD_API_URL}
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    depends_on:
      - test_db
    volumes:
      - api_data_ci:/var/www

  test_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    volumes:
      - test_db_data_ci:/var/lib/postgresql/data

volumes:
  api_data_ci:
  test_db_data_ci:
