version: '3.8'
services:
  test_db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    networks:
      - app-network
    volumes:
      - test_db_data_local:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '8080:80'
    networks:
      - app-network
    volumes:
      - pgadmin_data_local:/var/lib/pgadmin

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    env_file: .env
    image: stencil-auth0-storybook-local:latest
    ports:
      - '7910:7910'
    environment:
      IS_STORYBOOK: 'true'
      REDWOOD_API_URL: ${REDWOOD_API_URL}
    networks:
      - app-network
    volumes:
      - storybook_data_local:/var/www

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.prisma-studio
    env_file: .env
    image: stencil-auth0-prisma-studio-local:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5555:5555'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - prisma_studio_data_local:/var/www

volumes:
  test_db_data_local:
  pgadmin_data_local:
  storybook_data_local:
  prisma_studio_data_local:

networks:
  app-network:
