version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    environment:
      REDWOOD_API_URL: ${REDWOOD_API_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_REDIRECT_URI: ${AUTH0_REDIRECT_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    ports:
      - '8910:8910'
    networks:
      - app-network
    volumes:
      - web_data_local:/var/www

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    environment:
      REDWOOD_WEB_URL: ${REDWOOD_WEB_URL}
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      NODE_ENV: ${NODE_ENV}
      ENVIRONMENT: ${ENVIRONMENT}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    ports:
      - '8911:8911'
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - api_data_local:/var/www

  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
      - db_data_local:/var/lib/postgresql/data

volumes:
  web_data_local:
  api_data_local:
  db_data_local:

networks:
  app-network:
