version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8910:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8911:8911"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    depends_on:
      - db
      - test_db

  db:
    image: postgres:15
    volumes:
      - redwood_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  test_db:
    image: postgres:15
    volumes:
      - redwood_test_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  redwood_db_data:
  redwood_test_db_data:
