version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8910:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8911:8911"
