# Base stage for development, similar to your existing Dockerfile
FROM public.ecr.aws/docker/library/node:18.17.1-bookworm-slim as base
WORKDIR /app
COPY package.json yarn.lock redwood.toml graphql.config.js .
COPY api/package.json api/
COPY web/package.json web/
ENV HUSKY=0
RUN apt-get update && \
    apt-get install -y openssl libssl-dev && \
    yarn install --immutable --immutable-cache --parallel && \
    yarn cache clean && \
    rm -rf /var/lib/apt/lists/*

# Storybook stage
FROM base as storybook
COPY . .
RUN yarn install
ENV IS_STORYBOOK=true
EXPOSE 7910
CMD ["yarn", "rw", "storybook"]

# Prisma Studio stage
FROM base as prisma-studio
COPY . .
RUN yarn install
EXPOSE 5555
CMD ["yarn", "rw", "prisma", "studio"]
