FROM node:18

WORKDIR /usr/src/app

# Copy the root package.json, yarn.lock, and api folder
COPY package.json yarn.lock ./
COPY api/package.json api/

# Install dependencies at the root level
RUN yarn install

# Copy the rest of the api files
COPY api ./api

# Run Redwood CLI command for the api
CMD ["yarn", "workspace", "api", "rw", "dev", "api"]
