# ==
# Base
# ==
FROM node:18-alpine as base
WORKDIR /app
COPY package.json yarn.lock redwood.toml graphql.config.js .
COPY api/package.json api/
COPY web/package.json web/
ENV HUSKY=0
RUN apk add --update --no-cache openssl1.1-compat
RUN yarn install --immutable --immutable-cache

# ==
# Build
# ==
FROM base as builder
COPY api api
COPY web web
RUN yarn rw build api web
RUN yarn rw prisma generate

# ==
# Runners
# ==
# Runner for Storybook
FROM base AS storybook
WORKDIR /app
COPY --from=builder /app .
EXPOSE 7910
CMD ["yarn", "storybook"]

# Runner for Prisma Studio
FROM base AS prisma_studio
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5555
CMD ["yarn", "rw", "prisma", "studio"]

# Runner for the Nginx web server
FROM nginx:alpine AS web
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/web/dist .
EXPOSE 8910
CMD ["nginx", "-g", "daemon off;"]

# Runner for the API server
FROM node:18-alpine AS api
WORKDIR /app
COPY --from=builder /app .
COPY scripts scripts
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
EXPOSE 8911
CMD ["/app/entrypoint.sh"]
