# Base image
FROM node:20-slim AS base

RUN corepack enable
RUN apt-get update && apt-get install -y openssl libssl-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app
USER node

COPY --chown=node:node package.json yarn.lock redwood.toml ./
COPY --chown=node:node api/package.json api/
COPY --chown=node:node api/db ./api/db
RUN yarn install

EXPOSE 5555
CMD ["yarn", "rw", "prisma", "studio"]
