version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: web
    image: docker-ibraheem4-nginx-web-dev:latest
    ports:
      - "8910:8910"

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: storybook
    image: docker-ibraheem4-redwood-storybook-dev:latest
    ports:
      - "7910:7910"

  prisma_studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: prisma_studio
    image: docker-ibraheem4-redwood-prisma-studio-dev:latest
    ports:
      - "5555:5555"
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: api
    image: docker-ibraheem4-redwood-api-dev:latest
    ports:
      - "8911:8911"
    env_file:
      - .env
    environment:
      REDWOOD_API_URL: ${REDWOOD_API_URL}
      DATABASE_URL: ${DATABASE_URL}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    depends_on:
      - db
      - test_db

  db:
    image: postgres:15
    volumes:
      - redwood_db_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  test_db:
    image: postgres:15
    volumes:
      - redwood_test_db_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  redwood_db_data_dev:
  redwood_test_db_data_dev:
