version: '3.8'
services:
  web:
    build:
      context: .
      target: web
      dockerfile: Dockerfile.dev
    image: redwood-web-nginx-dev:latest
    ports:
      - "8910:8910"
    networks:
      - app-network
    volumes:
      - redwood_web_data_dev:/var/www

  api:
    build:
      context: .
      target: api
      dockerfile: Dockerfile.dev
    environment:
      REDWOOD_API_URL: ${REDWOOD_API_URL}
      REDWOOD_WEB_URL: ${REDWOOD_WEB_URL}
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      DISABLE_SIGNUP: ${DISABLE_SIGNUP}
      NODE_ENV: ${NODE_ENV}
      ENVIRONMENT: ${ENVIRONMENT}
    image: redwood-api-dev:latest
    ports:
      - "8911:8911"
      - "7910:7910"
      - "5555:5555"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - redwood_api_data_dev:/var/www

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEV}
    networks:
      - app-network
    volumes:
      - redwood_db_data_dev:/var/lib/postgresql/data

  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    networks:
      - app-network
    volumes:
      - redwood_test_db_data_dev:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - pgadmin_data_dev:/root/.pgadmin

volumes:
  redwood_web_data_dev:
  redwood_api_data_dev:
  redwood_db_data_dev:
  redwood_test_db_data_dev:
  pgadmin_data_dev:

networks:
  app-network:
