#####
# Documentation
# Redwood: https://render.com/docs/deploy-redwood
# YAML (all config values): https://render.com/docs/yaml-spec
#####

services:
  - name: redwood-stencil-web
    type: web
    env: static
    buildCommand: yarn install && yarn rw deploy render web
    staticPublishPath: ./web/dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SKIP_INSTALL_DEPS
        value: true
    routes:
      - type: rewrite
        source: /.redwood/functions/*
        #####
        # NOTE: replace destination api url after first deploy to Render
        # example:
        #   destination: https://myredwoodproject-api.onrender.com/*
        #####
        destination: https://redwood-stencil-api.onrender.com/*
      - type: rewrite
        source: /*
        destination: /200.html

  - name: redwood-stencil-api
    type: web
    plan: standard
    env: node
    region: oregon
    buildCommand: yarn && yarn rw build api
    startCommand: yarn rw deploy render api
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        fromDatabase:
          name: redwood-stencil-db
          property: connectionString

databases:
  - name: redwood-stencil-db
    region: oregon
