name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  common:
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      DISABLE_SIGNUP: ${{ secrets.DISABLE_SIGNUP }}
      REDWOOD_WEB_URL: ${{ secrets.REDWOOD_WEB_URL }}
      REDWOOD_API_URL: ${{ secrets.REDWOOD_API_URL }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      DATABASE_URL: postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@db:5432/${{secrets.POSTGRES_DB_DEV}}
      TEST_DATABASE_URL: postgresql://${{secrets.POSTGRES_USER}}:${{secrets.POSTGRES_PASSWORD}}@test_db:5432/${{secrets.POSTGRES_DB_TEST}}
      POSTGRES_DB_DEV: ${{ secrets.POSTGRES_DB_DEV }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB_PROD: ${{ secrets.POSTGRES_DB_PROD }}
      POSTGRES_DB_TEST: ${{ secrets.POSTGRES_DB_TEST }}
    strategy:
      matrix:
        command: ['yarn rw build', 'yarn rw lint', 'yarn rw test api --no-watch', 'yarn rw test web --no-watch']
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: docker-compose -f docker-compose.dev.yml build
      - name: Start the Dockerized RedwoodJS application
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Run command
        run: docker-compose -f docker-compose.dev.yml exec api ${{ matrix.command }}
      - name: Stopping the Dockerized RedwoodJS application
        run: docker-compose -f docker-compose.dev.yml down
