name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Install dependencies
        run: docker-compose exec api yarn install

      - name: Build RedwoodJS project
        run: docker-compose exec api yarn rw build

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Lint RedwoodJS project
        run: docker-compose exec api yarn rw lint

  test:
    runs-on: ubuntu-latest
    env:
      REDWOOD_API_URL: ***
      DATABASE_URL: postgresql://postgres:password@db:5432/redwood_dev
      TEST_DATABASE_URL: postgresql://postgres:password@db:5432/redwood_test

    steps:
      - uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Run migrations (if applicable)
        run: docker-compose exec api yarn rw prisma migrate deploy

      - name: Run API tests
        run: docker-compose exec api yarn rw test api --no-watch

      - name: Run Web tests
        run: docker-compose exec api yarn rw test web --no-watch
