name: CI/CD Pipeline

on:
  push:
    branches:
      - auth-auth0
  pull_request:
    branches:
      - auth-auth0

jobs:
  build_test_lint_publish:
    runs-on: ubuntu-latest
    env:
      REDWOOD_WEB_URL: ${{ secrets.REDWOOD_WEB_URL }}
      DISABLE_SIGNUP: ${{ secrets.DISABLE_SIGNUP }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      REDWOOD_API_URL: ${{ secrets.REDWOOD_API_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      POSTGRES_DB_DEV: ${{ secrets.POSTGRES_DB_DEV }}
      POSTGRES_DB_TEST: ${{ secrets.POSTGRES_DB_TEST }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB_DEV }}
      TEST_DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@test_db:5432/${{ secrets.POSTGRES_DB_TEST }}
      COMPOSE_PROJECT_NAME: stencil-auth0

    steps:
      - name: Capture start time
        run: echo "BUILD_START_TIME=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Make
        run: sudo apt-get update -y && sudo apt-get install -y make

      - name: Install dependencies
        run: yarn install

      - name: Build and start containers
        run: make up-ci

      - name: Install dependencies for API, Web
        run: make install-deps-ci

      - name: Build RedwoodJS project
        run: make build-ci

      - name: Lint RedwoodJS project
        run: make lint-ci

      - name: Run tests in parallel
        run: make test-ci

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('compose.yml') }}

      - name: Check ECR Repository Existence
        id: check-ecr
        run: |
          set +e
          exists=$(aws ecr describe-repositories --repository-names "stencil-auth0/web" --region ${{ secrets.AWS_REGION }} 2>&1)
          if [[ $exists == *"RepositoryNotFoundException"* ]]; then
            echo "::set-output name=repo_exists::false"
          else
            echo "::set-output name=repo_exists::true"
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker Images
        if: github.ref == 'refs/heads/auth-auth0'
        run: make build-docker

      - name: Tag Docker Images
        if: github.ref == 'refs/heads/auth-auth0'
        run: make tag-docker

      - name: Publish Docker Images to ECR
        if: steps.check-ecr.outputs.repo_exists == 'true'
        run: make publish-docker

      - name: Record build time
        if: github.ref == 'refs/heads/auth-auth0'
        run: echo "::warning file=build.log,line=2,col=5::Build took $(($(date +%s) - $BUILD_START_TIME)) seconds."

      - name: Cleanup
        run: make clean-ci

  deploy_to_aws:
    needs: build_test_lint_publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/auth-auth0' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS Copilot CLI
        run: |
          COPILOT_LATEST_VERSION=$(curl -s https://api.github.com/repos/aws/copilot-cli/releases/latest | grep 'tag_name' | cut -d '"' -f 4)
          echo "Latest Copilot Version: $COPILOT_LATEST_VERSION"
          COPILOT_BINARY='copilot-linux'
          COPILOT_URL="https://github.com/aws/copilot-cli/releases/download/$COPILOT_LATEST_VERSION/${COPILOT_BINARY}-$COPILOT_LATEST_VERSION"
          curl -Lo copilot-cli "${COPILOT_URL}"
          chmod +x copilot-cli
          sudo mv copilot-cli /usr/local/bin/copilot
          copilot --version

      - name: Initialize Copilot Application (if needed)
        run: copilot app init stencil-auth0 || echo "Application already initialized"

      - name: Initialize Copilot Test Environment (if needed)
        run: copilot env init --name test --app stencil-auth0 || echo "Environment already initialized"

      - name: Deploy Web Service to AWS Test Environment using Copilot
        run: copilot svc deploy --name web --env test
        env:
          DISABLE_SIGNUP: ${{ secrets.DISABLE_SIGNUP }}

      - name: Deploy API Service to AWS Test Environment using Copilot
        run: copilot svc deploy --name api --env test
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}

      - name: Record deployment time
        run: |
          DEPLOY_END_TIME=$(date +%s)
          DEPLOY_DURATION=$((DEPLOY_END_TIME - $DEPLOY_START_TIME))
          echo "::notice::Deployment took ${DEPLOY_DURATION} seconds."
