name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['yarn rw build', 'yarn rw lint', 'yarn rw test api --no-watch', 'yarn rw test web --no-watch']
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: docker-compose -f docker-compose.dev.yml build
      - name: Start the Dockerized RedwoodJS application
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Run command
        run: docker-compose -f docker-compose.dev.yml exec api ${{ matrix.command }}
      - name: Stopping the Dockerized RedwoodJS application
        run: docker-compose -f docker-compose.dev.yml down
