name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_test_lint_publish:
    runs-on: ubuntu-latest
    env:
      REDWOOD_API_URL: http://api:8911
      POSTGRES_DB_DEV: ${{ secrets.POSTGRES_DB_DEV }}
      POSTGRES_DB_TEST: ${{ secrets.POSTGRES_DB_TEST }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB_DEV }}
      TEST_DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@test_db:5432/${{ secrets.POSTGRES_DB_TEST }}

    steps:
      - name: Record start time
        run: echo "BUILD_START_TIME=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Install dependencies
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn install

      - name: Build RedwoodJS project
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn rw build

      # Lint
      - name: Lint RedwoodJS project
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn rw lint

      # Test
      - name: Run Web tests
        run: docker-compose -f docker-compose.ci.yml exec -T api yarn rw test web --no-watch

      # Publish
      - name: Tag Docker Images
        run: |
          docker tag docker-ibraheem4-nginx-web-dev:latest ibraheem4/docker-ibraheem4-nginx-web-dev:latest
          docker tag docker-ibraheem4-redwood-api-dev:latest ibraheem4/docker-ibraheem4-redwood-api-dev:latest

      - name: Publish Docker Images
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ibraheem4/docker-ibraheem4-nginx-web-dev:latest
          docker push ibraheem4/docker-ibraheem4-redwood-api-dev:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Build Information
        run: |
          web_image_size=$(docker images ibraheem4/docker-ibraheem4-nginx-web-dev:latest --format "{{.Size}}")
          api_image_size=$(docker images ibraheem4/docker-ibraheem4-redwood-api-dev:latest --format "{{.Size}}")
          echo "::warning file=build.log,line=1,col=5::Web Image Size: $web_image_size | API Image Size: $api_image_size"

      - name: Record build time
        run: echo "Build took $(($(date +%s) - $BUILD_START_TIME)) seconds."
